# #!Sign In
POST http://localhost:3001/api/v1/signin
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"test123"
}
# #!Sign Up

# POST http://localhost:3001/api/v1/signup
# Content-Type: application/json

# {
#   "email":"test@test.com",
#   "password":"test123"
# }